export const ACCESS_TOKEN_NOT_VALID_OR_EXPIRED = 1;
export const AUTHORIZATION_HEADER_NOT_FOUND = 2;
export const LOGIN_FAILED_PASSWORD_NOT_CORRECT = 3;
export const ACCOUNT_NOT_FOUND = 4;

export const EMPLOYEE_NOT_FOUND = 101;

export const EMPLOYEE_PAYMENT_TYPE_NOT_FOUND = 201;

export const EMPLOYEE_PAYMENT_NOT_FOUND = 301;
export const CREATE_SALARY_EMPLOYEE_PAYMENT_FAILED_THERE_IS_ONE_ALREADY_FOR_THIS_MONTH = 302;
